#!/bin/bash

# Documentation is typically generated by Github Action, but can be manually
# generated with this script. Note that to make it live, it must be placed in
# the gh-pages branch.

(pip3 install pdoc3);
(pdoc --html $(pwd)/../eyecite --output-dir $(pwd) --force);
sed -i '' -E 's#(AhocorasickTokenizer\().*(markup_text:)#\1),<br>\2#g' eyecite/find.html eyecite/index.html
