name: CI

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install devbox
      uses: jetpack-io/devbox-install-action@v0.8.0

    - run: devbox run pdm install 
    - run: devbox run pre-commit run --all-files

